name: Release build
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Konstructor fat jar
        run: gradle -Prelease=true backend:shadowJar && cp backend/build/libs/backend-all.jar backend/build/libs/konstructor.jar

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            backend/build/libs/konstructor.jar

